# Generated by Django 5.0 on 2023-12-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="telefon",
            field=models.CharField(default="-", max_length=100),
        ),
    ]
